name: Deploy docs
on:
  push:
    # tags: ['[0-9]+.[0-9]+.*']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            make  

      - uses: actions/cache@v2
        name: Set up caches
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements-dev.txt
      
      - name: Run tests
        run: |
          make test

      - name: Build docs
        run: |
          make -f sphinx.makefile html

      - name: Deploy docs
        env:
          GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: bash .github/deploy-gh-pages.sh

